### ISSUE TITLE
no method call allowed in a foreach

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#10]
http://paste.pocoo.org/show/142753/

gets

<pre>./value-in-foreach.ooc:11:24: [ERROR] Couldn't resolve type ArrayList<String> of foreach's collection.
    for(e: String in a get()) {
                       ^^^
</pre>

**Comment by nddrylliog** [comment]
Fix committed. Thx for reporting =)

http://github.com/amoswenger/ooc/commit/6cafde7c8f70d2477ccb2c46bc0d3fa513ced277
