### ISSUE TITLE
gcc errors when calling a generic method without `this`

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#13]
http://paste.pocoo.org/show/142907/

gives:

<pre>ooc_tmp/bugs/generic-string.c: In function 'A_foo_impl':
ooc_tmp/bugs/generic-string.c:23: error: lvalue required as unary '&' operand
ooc_tmp/bugs/generic-string.c:23: error: too few arguments to function 'A_test'
</pre>

Using `this test(123)` lets that error disappear.

**Comment by nddrylliog** [comment]
Fix committed. Thanks =)

http://github.com/amoswenger/ooc/commit/cb36e222505cce9d08a5204230c3400fa622c656
