### ISSUE TITLE
inherited methods cause gcc errors

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#14]
http://paste.pocoo.org/show/142908/

causes:

<pre>
ooc_tmp/bugs/inheritance.c: In function 'C_class':
ooc_tmp/bugs/inheritance.c:205: error: unknown field 'foo' specified in initializer
ooc_tmp/bugs/inheritance.c:205: warning: excess elements in struct initializer
ooc_tmp/bugs/inheritance.c:205: warning: (near initialization for 'class.__super__')
C compiler failed, aborting compilation process
</pre>

**Comment by nddrylliog** [comment]
Fixed & committed.

http://github.com/amoswenger/ooc/commit/588aa0f77b4c2dcfc4857821ab591b28afbb1452
