### ISSUE TITLE
Deriving from exception makes gcc sad

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#15]
<pre>[fred@ork bugs]$ cat funny-exception.ooc 
Foo: class extends Exception {}
[fred@ork bugs]$ ooc funny-exception.ooc 
ooc_tmp/bugs/funny-exception.c: In function 'Foo_init':
ooc_tmp/bugs/funny-exception.c:65: error: too few arguments to function '((struct lang__ExceptionClass *)((struct lang__Object *)this)->class)->init'
C compiler failed, aborting compilation process
</pre>

=)

**Comment by nddrylliog** [comment]
Fixed & committed. This was in fact a wrong usage of ooc and a helpful compiler error message has been added.

http://github.com/amoswenger/ooc/commit/6581cf95028b67b0c7053e9dd3c97e7d74002c42
