### ISSUE TITLE
Sometimes, I get 'Tinkerer goind round in circles'

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#16]
For example, if I compile a script using a local package, I get:

<pre>Tinkerer goind round in circles</pre>

**Comment by nddrylliog** [comment]
git commit -a -m "Fixed #16, aka 'Tinkerer going round in circles'. The offending code was in Assignment. Now, whenever the Tinkerer is going round in circles, in the fatal round it signals the offending nodes. Remember that you can adjust the number of the fatal round with the -blowup= option. The default is at 128."
[master f4290bb] Fixed #16, aka 'Tinkerer going round in circles'. The offending code was in Assignment. Now, whenever the Tinkerer is going round in circles, in the fatal round it signals the offending nodes. Remember that you can adjust the number of the fatal round with the -blowup= option. The default is at 128.

http://github.com/amoswenger/ooc/commit/f4290bbeeaf7d5a82195d4fb979be76b3363e242
