### ISSUE TITLE
[] operator overloading does not work for strings

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#19]
<pre>A: class {}

operator [] (a: A, index: Int) -> Int {
    return 1
}

main: func {
    s := "hello"
    ch := s[0]
    a := A new()
    one := a[0]
}
</pre>

translates to:

<pre>   lang__String s = "hello";
    lang__String ch = s[0];
    A *a = A_new();
    lang__Int one = __OP_IDX_A_Int(a, 0);
</pre>

There is an overloaded [] operator in lang/String, but it's not used

**Comment by nddrylliog** [comment]
Fiiiixxeeed.
Damn C where Numeric types are equivalent. haha.
