### ISSUE TITLE
ooc should disallow names that c disallows

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#20]
For example, this is valid ooc code:

<pre>char := 1</pre>

But gcc doesn't want it:

<pre>In file included from ooc_tmp/bugs/names.c:2:
ooc_tmp/bugs/names.h:24: error: two or more data types in declaration specifiers
ooc_tmp/bugs/names.h:24: warning: useless type name in empty declaration
ooc_tmp/bugs/names.c: In function '_names_load':
ooc_tmp/bugs/names.c:26: error: expected identifier or '(' before '=' token
C compiler failed, aborting compilation process
</pre>

**Comment by nddrylliog** [comment]
Fixed. Added checks for all C99 keywords.
