### ISSUE TITLE
Generics/Pattern Matching: error when getting val from different function

### ISSUE THREAD

**Issue by showstopper** [fasterthanlime/jooc-legacy#22]
http://paste.pocoo.org/show/144129/
-> ooc_tmp/bugs/test.c:24: error: incompatible types when assigning to type »lang__String« from type »lang__Double«
ooc_tmp/bugs/test.c:26: error: incompatible types when assigning to type »lang__String« from type »lang__Bool«

**Comment by nddrylliog** [comment]
Fififixed. thanks for reporting =) It was a more generic issue with assigning from a generic typed expr to a non-generic typed var. Example in tests/generics/018-*
