### ISSUE TITLE
Generic type undefined

### ISSUE THREAD

**Issue by mt2d2** [fasterthanlime/jooc-legacy#24]
I'm trying to implement a basic Stack using an ArrayList as a backend. Stack is a generic class, but functions with generic parameters don't seem to know their type. Instead there's an error:

./sdk/structs/Stack.ooc:12:28: [ERROR] Couldn't resolve type
        printf("adding: %d\n", element)
                                 ^^^
I've added Stack to the repo so people can play with it/test it.

**Comment by nddrylliog** [comment]
Wrong usage of ooc, you should add a cast to Int, here e.g.

<pre>
printf("adding: %d", element as Int)
</pre>


But we went over that already =)
