### ISSUE TITLE
Add -hardass flag

### ISSUE THREAD

**Issue by nddrylliog** [fasterthanlime/jooc-legacy#25]
Not everyone likes a compiler soft and friendly.

Those who want tough love shouldn't be set apart.

**Comment by ioquatix** [comment]
I agree.

**Comment by nddrylliog** [comment]
Will definitely be implemented in http://github.com/nddrylliog/rock (you sissies)

**Comment by nddrylliog** [comment]
Since it won't be implemented in j/ooc, closed here.
