### ISSUE TITLE
wrong use of memcpy when returning generic members in a generic function

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#27]
This code:

<pre>
Box: class <T> {
    value: T

    init: func (v: T) {
        value = v
    }
}

test: func <T> (T: Class) -> T {
    box := Box<String> new("Hey there!")
    box value as T
}

main: func {
    test(String) println()
}
</pre>

should print "Hey there!", but instead it prints a strange character.

The C code for `test` looks like this:

<pre>void test(lang__Pointer __returnArg, lang__Class *T)
{
    lang__String tparam = "Hey there!";
    Box *box = Box_new(String_class(), (uint8_t*) &tparam);
    if (__returnArg)
    {
        memcpy(__returnArg, ((lang__Pointer) (&(box->value))), T->size);
    }
    return;
}
</pre>

where this line:

<pre>memcpy(__returnArg, ((lang__Pointer) (&(box->value))), T->size);</pre>

should be:

<pre>memcpy(__returnArg, ((lang__Pointer) ((box->value))), T->size);</pre>

With this change applied, it works \o/

**Comment by nddrylliog** [comment]
Fi-fi-fi-fixed. Thanks for reporting, fred.
http://github.com/nddrylliog/ooc/commit/c1ff295652dd592417f23b8041817894ba0384dd
