### ISSUE TITLE
Old for() doesn't work

### ISSUE THREAD

**Issue by richardwtf** [fasterthanlime/jooc-legacy#31]
The compiler doesn't like the standard `for` format.

I.e.:

`for (i := 0; i < limit; i += step) { foo }`

results in an error like

`./test.ooc:9:3: Expected statement in function body. Found 'for' instead.`

**Comment by nddrylliog** [comment]
Added. Thanks for reporting =)

http://github.com/nddrylliog/ooc/commit/670d568359fc10e76ccf792a775540e6dc654547

Added regular for in the syntax, e.g. for(i := 0; i < limit; i += step) 
{}. Example in tests/statements/012-regular-for.ooc
