### ISSUE TITLE
Respect OOC_DIST

### ISSUE THREAD

**Issue by defunkt** [fasterthanlime/jooc-legacy#33]
http://ooc-lang.org/setup says:

"Maybe you want to edit the file to set where the distribution is located. This is done by changing the path of OOC_DIST to the specific path"

Yet this only works by modifying the `utils/ooc` script directly. I have a commit which fixes this:

http://github.com/defunkt/ooc/commit/e3d483d84fd2024358403fbe9dd756745fb39324

**Comment by nddrylliog** [comment]
Merged.
Thanks for the patch =)
(and I actually learned some more bash. I would've done a simple OOC_DIST?=/opt/ooc)
