### ISSUE TITLE
operator overloads as static methods

### ISSUE THREAD

**Issue by solson** [fasterthanlime/jooc-legacy#35]
It would be nice to have syntax like this:

```
    Env["HOME"]
```

for getting environment variables and this:

```
    Env["PATH"] = "/my/special/bins"
```

for setting env variables

what we need to do that is operator overloads as static methods

**Comment by nddrylliog** [comment]
I actually think it's a feature that is seldom needed and would actually make code less clear/readable in most cases, so I'm against it, if you don't have a really compelling argument for it.

**Comment by solson** [comment]
The way operator overloads are written in ooc, I agree. It's not too much harder to write:
    Env get("HOME")
    Env set("PATH", "/my/special/bins")
Although, I'm really not a fan of setter methods that don't use =

**Comment by nddrylliog** [comment]
Setter methods that don't use "="? What do you mean?

**Comment by solson** [comment]
It's makes a lot of sense for all methods of assignment to use "=". We use foo := 1 for variables and foo bar = "baz" for member variables. Often we need special setter methods that set a member variable and do something else at the same time. Why should we use something like foo setBar("baz") or Env set("PATH", "/my/special/bin") for custom setter methods?

**Comment by solson** [comment]
Env in fact could just act like a Hash using []=, but currently to do that it would have to not be a Class

**Comment by nddrylliog** [comment]
Yeah, 'Env' could just be a global variable of type HashMap. Or rather, a subclass of it, with an overloaded set() and get().

With that in mind, are "operator overloads as static methods" still useful, in your opinion?

**Comment by solson** [comment]
I don't think they are worth the pain of being implemented if we can work around them.
