### ISSUE TITLE
evil C cast done when invoking a generic function with a casted generic argument

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#37]
Wooohooo, long description.

http://paste.pocoo.org/show/149460/

generates:

<pre>ooc_tmp/bugs/evil-cast.c: In function '_evil_cast_load':
ooc_tmp/bugs/evil-cast.c:19: error: lvalue required as unary '&' operand
C compiler failed, aborting compilation process
</pre>

because of:

<pre>       fun(UChar_class(), 123, (uint8_t*) &((unsigned char) (456)));
</pre>

We don't need the `unsigned char` cast here. :)

**Comment by nddrylliog** [comment]
Fixed =) The problem was more than that, actually.

http://github.com/nddrylliog/ooc/commit/b9c690773222861a7bff803335d8fc09537eac17
