### ISSUE TITLE
building without linking to the lib

### ISSUE THREAD

**Issue by solson** [fasterthanlime/jooc-legacy#47]
I am having problems building in oos. I think the best solution would be to build the ooc sdk as a standalone library and then build all the other parts without the library linked in, and link it manually afterwards.

Basically, I just want 'ooc --build-sdk' and 'ooc --do-not-link-sdk', but you can pick better names.

**Comment by nddrylliog** [comment]
Wouldn't this be better implemented as the --dont-link= and -only-link= commandline options? You could then specify folders/files that you want/don't want to be included in the compiled C, so in your case you would do something like:

<pre>
ooc -c -driver=sequence -only-link=$OOC_DIST/sdk -outlib=ooc-sdk.a
ooc -c -driver=sequence -dont-link=$OOC_DIST/sdk -outlib=oos-core.a
ld ooc-sdk.a oos-core.a -o oos
</pre>


This is both more flexible and easier to implement in the compiler. Would it do the trick for you?

**Comment by solson** [comment]
That should work. Will -only-link work without giving any source files like that?

**Comment by nddrylliog** [comment]
Well, no.

ooc, by default, compiles (and links) only what you need. so if you have to give it a source file so it can parse everything and know which parts of the sdk you need.

so yeah, my examples are flawed, sorry :/ but I think you got the idea, it's just a matter of what would be put in the .a
