### ISSUE TITLE
'match' in class with class function requires 'this' (j/ooc)

### ISSUE THREAD

**Issue by showstopper** [fasterthanlime/jooc-legacy#48]
http://paste.pocoo.org/show/157654/
results in error message:
[ERROR] Can't resolve type of left Parenthesis: (test()) operand. Wtf?
            case true => return

Calling " match this test()" works fine
[EDIT:] same code works fine with rock

**Comment by nddrylliog** [comment]
Apparently it's a parsing problem. Parenthesizing it fixes it, e.g.

<pre>
match (test()) {
</pre>


It doesn't look like an easy fix to j/ooc, and won't happen in rock anyway, so I don't think it's worth the headache.

**Comment by showstopper** [comment]
I agree. Working with rock and the workaround with the parenthesis it's no problem.

**Comment by nddrylliog** [comment]
Closing, then =)
