### ISSUE TITLE
missing escape code

### ISSUE THREAD

**Issue by solson** [fasterthanlime/jooc-legacy#53]
ooc doesn't recogize '\v' (vertical tab), but C does.

**Comment by nddrylliog** [comment]
Fixed 

http://github.com/nddrylliog/ooc/commit/78a7f2a5bc220c982fbee021afd456fc787e4ca0

Thanks for reporting!

**Comment by solson** [comment]
Now it tells me this:
    src/ooc-sdk/lang/BasicTypes.ooc:73:26: Invalid escape sequence : \\null
                    this == '\v'
                             ^^

**Comment by nddrylliog** [comment]
Oh, right, char literals, too.

Fixed the fix:
http://github.com/nddrylliog/ooc/commit/95bc10a5083351af628959cb62b8c5631c97fb88
