### ISSUE TITLE
HashMap[] operator not correctly translated

### ISSUE THREAD

**Issue by showstopper** [fasterthanlime/jooc-legacy#56]
http://paste.pocoo.org/show/159127/
creates the error-message:
     In function 'main': ooc_tmp/bugs/hashmap_get.c:19: error: array subscript is not an integer
C compiler failed, aborting compilation process
Apparently 
    HashMap<Int> ["a"] 
is not correctly translated to 
    HashMap<Int> get("a")
but to the arrayfield operator instead
     b += a[a];

EDIT: It should be b += a["a"] not a[a], but the problem and the error-message are the same

**Comment by nddrylliog** [comment]
Fixed!

http://github.com/nddrylliog/ooc/commit/1ae1d175cf70dcb0bac135f739bf7b69d1ab00ff

This was a biggie, thanks, I have cleaned up j/ooc's code a little bit and fixed a few other bugs while I was at it..

And best thing - rock still compiles and runs correctly =)
