### ISSUE TITLE
overloaded comparison operators only work once in a comparison

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#6]
http://paste.pocoo.org/show/142748/

Look at the generated C code - it's using the _OP_\* function only once

**Comment by nddrylliog** [comment]
Fixed & committed. It was the whole operator precedence that was broken in ooc. It's all fixed now =)

http://github.com/amoswenger/ooc/commit/83f553951c44ec537415fe59f88216f6f3e00937
