### ISSUE TITLE
Link error due to incorrectly generated code when calling a returned closure

### ISSUE THREAD

**Issue by joshthecoder** [fasterthanlime/jooc-legacy#62]
See gist #287417

**Comment by joshthecoder** [comment]
LInk to gist: http://gist.github.com/287417

**Comment by fredreichbier** [comment]
Keep module information for FunctionCalls on variables and use them to construct the full variable name. Closed by 6725e7d5c73dc4af32f77ba4a5c1db378d0df1ce.

**Comment by fredreichbier** [comment]
6725e7d5c73dc4af32f77ba4a5c1db378d0df1ce fixes this, thanks for reporting!
