### ISSUE TITLE
Casting a class instance to its base does not invoke the proper method

### ISSUE THREAD

**Issue by joshthecoder** [fasterthanlime/jooc-legacy#63]
When calling a casted child class, its base class method is not being invoked.
Instead the child method is still being called.

Here is a gist that shows this issue with the results: http://gist.github.com/287513

**Comment by mt2d2** [comment]
I'm not positive, but doesn't Java work the same way as ooc? I'd be interested in seeing the cpp code, too. A quick spin at translating to Java… http://gist.github.com/287605

**Comment by joshthecoder** [comment]
Okay so in c++ if you mark base class methods as virtual, then the child methods will be used. So the OOC way is much like virtual methods. I guess this works okay for me. Not sure if we want to mimic non-virtual methods or not in ooc.

Going to close this issue since this is not a bug, but a design issue.

**Comment by nddrylliog** [comment]
Not a design issue either =)

It should probably be in the docs somewhere, but in ooc (as in Java) methods are non-final (e.g. virtual) by default. Use the 'final' keyword to make them final (e.g. non-virtual).

Here, complete examples both in ooc and C++, showing that both have the intended behaviour =)

http://gist.github.com/287811
