### ISSUE TITLE
Iteration inside a member function overwrites instance variables

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#64]
http://gist.github.com/297133

prints

<pre>One
Three</pre>

I think it shouldn't, it should just create a new local variable `name` in `test`.

**Comment by nddrylliog** [comment]
Now variable accesses in foreaches always create local variable decls, and never resolve to something else (e.g. instance vars). (Also, added 007-swap generic test. Fun! ) This closed by e389e474de4f7c7e3b1835ffd41fd7ba4eb9081a
