### ISSUE TITLE
strange error message if a foreach type is missing

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#7]
This code:

http://paste.pocoo.org/show/142751/

says:

<pre>./foreach-type-missing.ooc:8:9: [ERROR] Couldn't resolve access to s.
        s println()
        ^</pre>

I find that obscure :P

**Comment by nddrylliog** [comment]
Fixed and committed.
Now foreach without type should work everywhere =)

http://github.com/amoswenger/ooc/commit/105f8f6e81526b7b950d30a940e6eb578eea5296
