### ISSUE TITLE
global variables can't be objects

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#9]
http://paste.pocoo.org/show/142752/

throws:

<pre>^C(dev)[fred@ork bugs]$ ooc global.ooc 
In file included from ooc_tmp/bugs/global.c:2:
ooc_tmp/bugs/global.h:30: warning: implicit declaration of function 'Test_new'
ooc_tmp/bugs/global.h:30: warning: initialization makes pointer from integer without a cast
ooc_tmp/bugs/global.h:30: error: initializer element is not constant
ooc_tmp/bugs/global.h:51: error: conflicting types for 'Test_new'
ooc_tmp/bugs/global.h:30: note: previous implicit declaration of 'Test_new' was here
ooc_tmp/bugs/global.c:66: error: conflicting types for 'Test_new'
ooc_tmp/bugs/global.h:30: note: previous implicit declaration of 'Test_new' was here
C compiler failed, aborting compilation process
</pre>

**Comment by nddrylliog** [comment]
Fixed.

http://github.com/amoswenger/ooc/commit/fa3a0659dbf168c9043c7078be64ccf69d55566e
